//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OhtaPark
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public string OrderCode { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string OrderTime { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<System.DateTime> ClosureDate { get; set; }
        public string RentalTime { get; set; }
        public Nullable<int> ServiceId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Service Service { get; set; }
    }
}
